#! /usr/bin/env node

import terminal from './src/bootstrap/terminal.js';

console.log();

const [ ,, tag, ...args ] = process.argv;

try {
  await terminal.command(tag, args);
} catch(error) {
  console.log(error);
  process.exit(1);
}

process.exit(0);
